//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnAPresa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carter_DnAHistory
    {
        public string EmployID { get; set; }
        public string lastname { get; set; }
        public string frstname { get; set; }
        public string midlname { get; set; }
        public string emplclas { get; set; }
        public string db { get; set; }
        public string testsel { get; set; }
        public System.DateTime Report_DateTime { get; set; }
    }
}
