//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnAPresa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class labelfile
    {
        public string labeldefinition { get; set; }
        public string name { get; set; }
        public string abbr { get; set; }
        public Nullable<int> code { get; set; }
        public string locked { get; set; }
        public string userlabelname { get; set; }
        public string edicode { get; set; }
        public byte[] timestamp { get; set; }
        public string systemcode { get; set; }
        public string retired { get; set; }
        public string inventory_item { get; set; }
        public string acct_db { get; set; }
        public string ic_clear_glnum { get; set; }
        public string acct_server { get; set; }
        public string pyt_itemcode { get; set; }
        public string teamleader_email { get; set; }
        public string auto_complete { get; set; }
        public string label_ExtraString1 { get; set; }
        public string exclude_from_creditcheck { get; set; }
        public string label_extrastring2 { get; set; }
        public string create_move { get; set; }
        public string param1 { get; set; }
        public string param2 { get; set; }
        public string param1_label { get; set; }
        public string param2_label { get; set; }
        public string label_extrastring1_label { get; set; }
        public string label_extrastring2_label { get; set; }
        public string label_extrastring3 { get; set; }
        public string label_extrastring4 { get; set; }
        public string label_extrastring5 { get; set; }
        public string label_extrastring6 { get; set; }
        public string global_label { get; set; }
    }
}
