//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnAPresa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DNA_CurrentEmployees
    {
        public string EmployeeNumber { get; set; }
        public string EmployeeFullName { get; set; }
        public string F3 { get; set; }
        public string Status { get; set; }
        public string Tier1 { get; set; }
        public string Tier2 { get; set; }
        public string Tier3 { get; set; }
        public string Tier4 { get; set; }
        public string Tier5 { get; set; }
        public string Tier6 { get; set; }
        public string Tier8 { get; set; }
        public string EmployeeLastName { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeMiddleName { get; set; }
    }
}
